# Generated by Django 3.1.4 on 2020-12-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('thumbnail', models.CharField(max_length=100, null=True)),
                ('user_rank', models.CharField(choices=[('', 'Select Tag'), ('0', '사원'), ('1', '대리'), ('2', '팀장'), ('3', '과장'), ('4', '부장'), ('5', '사장')], max_length=100)),
                ('birth', models.CharField(max_length=100)),
            ],
        ),
    ]
