# Generated by Django 3.1.4 on 2020-12-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
