# Generated by Django 3.1.4 on 2020-12-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20201216_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photo',
        ),
        migrations.AddField(
            model_name='user',
            name='task',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
