# Generated by Django 3.1.4 on 2020-12-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20201216_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_rank',
            field=models.CharField(choices=[('', 'Select Tag'), ('사원', '사원'), ('대리', '대리'), ('팀장', '팀장'), ('과장', '과장'), ('부장', '부장'), ('사장', '사장')], max_length=100),
        ),
    ]
